namespace InfalibleRealEstate.Models.Datalist;

public class ProvinciasyCiudades
{
    public static readonly List<string> Provincias = new()
    {
        "Azua",
        "Bahoruco",
        "Barahona",
        "Dajabón",
        "Distrito Nacional",
        "Duarte",
        "El Seibo",
        "Elías Piña",
        "Espaillat",
        "Hato Mayor",
        "Hermanas Mirabal",
        "Independencia",
        "La Altagracia",
        "La Romana",
        "La Vega",
        "María Trinidad Sánchez",
        "Monseñor Nouel",
        "Monte Cristi",
        "Monte Plata",
        "Pedernales",
        "Peravia",
        "Puerto Plata",
        "Samaná",
        "San Cristóbal",
        "San José de Ocoa",
        "San Juan",
        "San Pedro de Macorís",
        "Sánchez Ramírez",
        "Santiago",
        "Santiago Rodríguez",
        "Santo Domingo",
        "Valverde"
    };

    public static readonly List<string> Ciudades = new()
    {
        "Santo Domingo",
        "Santiago",
        "San Francisco de Macorís",
        "La Vega",
        "Puerto Plata",
        "San Pedro de Macorís",
        "San Cristóbal",
        "Bonao",
        "Moca",
        "Higüey",
        "Barahona",
        "Azua",
        "San Juan de la Maguana",
        "Cotuí",
        "Nagua",
        "Dajabón",
        "Monte Cristi",
        "El Seibo",
        "Hato Mayor",
        "Samaná",
        "Pedernales",
        "Neiba",
        "Jimani",
        "Salcedo",
        "Villa Altagracia",
        "Bani",
        "Boca Chica",
        "Villa Mella",
        "Los Alcarrizos",
        "San José de Ocoa",
        "Cabrera"
    };
}
